image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:

  java -Duser.language=en -Duser.country=US -jar app-mbank.jar
  - chmod + gradlew
build_script:
  - ./gradlew test --info